[phases.setup]
nixPkgs = ["nodejs_18", "python39", "pip"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd ../backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd ../backend && python manage.py makemigrations",
  "cd ../backend && python manage.py migrate",
  "cd ../backend && python setup_data.py",
  "cd ../backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:$PORT"