[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/"
restartPolicyType = "ON_FAILURE"

[deploy.variables]
PYTHON_VERSION = "3.9.16"
NODE_VERSION = "18"